#Regresión logística

Autora: Vanessa

Fecha: 2026-01-19

Objetivo: Realizar un modelo de regresión logística.

In [1]:
import pandas as pd
import numpy as np

#ETL
Importar el dataset

In [11]:
df = pd.read_csv("/content/data.csv", sep=";")

In [12]:
df.head()

cliente_id     genero  edad pais    ciudad segmento_cliente  es_mayor  \
0  0002-ORFBO   Femenino  36.0  USA  New York             PYME         0   
1  0003-MKNFE  Masculino  45.0  USA  New York      Residencial         0   
2  0004-TLHLJ  Masculino  36.0  USA  New York             PYME         0   
3  0011-IGKFF  Masculino   NaN  USA  New York             PYME         1   
4  0013-EXCHZ   Femenino  48.0  USA  New York             PYME         1   

  tiene_pareja tiene_dependientes                 latitud  ... dias_mora  \
0           Si                 Si  40.726.363.407.709.900  ...         0   
1           No                 No  40.678.021.618.445.700  ...         0   
2           No                 No     406.381.342.463.984  ...         0   
3           Si                 No   4.068.332.108.396.670  ...         0   
4           Si                 No  40.764.546.070.630.000  ...         0   

  cambio_plan_reciente  downgrade_reciente visitas_app_mensual  \
0                    1                   0                  66   
1                    0                   0                  51   
2                    0                   0                   5   
3                    0                   0                   9   
4                    0                   0                  37   

  tiempo_sesion_promedio  features_nuevas_usadas  ultimo_contacto_soporte  \
0                  11.51                       3               27/11/2025   
1                  20.17                       6               10/11/2025   
2                 109.44                       5               29/10/2025   
3                  90.94                       0               14/11/2025   
4                 113.28                       8                12/8/2025   

  competidores_area  ofertas_recibidas precio_vs_mercado  
0                 4                  0       Competitivo  
1                 1                  2              Alto  
2                 6                  2       Competitivo  
3                 2                  3       Competitivo  
4                 1                  0              Alto  

[5 rows x 67 columns]

In [13]:
df.shape

(9701, 67)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9701 entries, 0 to 9700
Data columns (total 67 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   cliente_id               9701 non-null   object 
 1   genero                   9701 non-null   object 
 2   edad                     8925 non-null   float64
 3   pais                     9701 non-null   object 
 4   ciudad                   9701 non-null   object 
 5   segmento_cliente         9701 non-null   object 
 6   es_mayor                 9701 non-null   int64  
 7   tiene_pareja             9701 non-null   object 
 8   tiene_dependientes       9701 non-null   object 
 9   latitud                  9701 non-null   object 
 10  longitud                 9701 non-null   object 
 11  borough                  9701 non-null   object 
 12  codigo_postal            9701 non-null   int64  
 13  estado                   9701 non-null   object 
 14  fecha_registro          

In [15]:
df.describe()

edad     es_mayor  codigo_postal  ingreso_mediano  \
count  8925.000000  9701.000000    9701.000000      9701.000000   
mean     43.971092     0.161324   10832.161324     66460.674157   
std      12.248348     0.367848     514.281652     14676.147445   
min      18.000000     0.000000   10001.000000     42000.000000   
25%      35.000000     0.000000   10312.000000     63000.000000   
50%      44.000000     0.000000   11114.000000     72000.000000   
75%      53.000000     0.000000   11239.000000     82000.000000   
max      74.000000     1.000000   11696.000000     85000.000000   

       densidad_poblacional   antiguedad  errores_pago  conexiones_mensuales  \
count           9701.000000  9701.000000   9701.000000           9701.000000   
mean           14736.604474    32.898876      0.599938             83.102361   
std             7302.961070    25.605834      1.399792             39.669341   
min             3200.000000     0.000000      0.000000              5.000000   
25%             8500.000000     9.000000      0.000000             52.000000   
50%            13000.000000    29.000000      0.000000             84.000000   
75%            14000.000000    56.000000      1.000000            118.000000   
max            28000.000000   179.000000     11.000000            149.000000   

       dias_activos_semanales  promedio_conexion  ...  cancelacion  \
count             9701.000000        9701.000000  ...  9701.000000   
mean                 4.945057          73.687649  ...     0.156891   
std                  1.676635          28.569725  ...     0.363717   
min                  1.000000          10.050000  ...     0.000000   
25%                  4.000000          52.880000  ...     0.000000   
50%                  5.000000          75.480000  ...     0.000000   
75%                  6.000000          97.740000  ...     0.000000   
max                  7.000000         120.000000  ...     1.000000   

       intentos_cobro_fallidos    dias_mora  cambio_plan_reciente  \
count              9701.000000  9701.000000           9701.000000   
mean                  0.996701     7.632203              0.256365   
std                   1.067799    10.032225              0.436648   
min                   0.000000     0.000000              0.000000   
25%                   0.000000     0.000000              0.000000   
50%                   1.000000     5.000000              0.000000   
75%                   2.000000    15.000000              1.000000   
max                   3.000000    30.000000              1.000000   

       downgrade_reciente  visitas_app_mensual  tiempo_sesion_promedio  \
count         9701.000000          9701.000000             9701.000000   
mean             0.213586            49.405731               62.678872   
std              0.409859            28.884164               33.236751   
min              0.000000             0.000000                5.010000   
25%              0.000000            24.000000               34.230000   
50%              0.000000            50.000000               62.360000   
75%              0.000000            74.000000               91.690000   
max              1.000000            99.000000              119.990000   

       features_nuevas_usadas  competidores_area  ofertas_recibidas  
count             9701.000000        9701.000000        9701.000000  
mean                 4.984641           4.503762           0.981858  
std                  3.153246           2.284261           1.065524  
min                  0.000000           1.000000           0.000000  
25%                  2.000000           2.000000           0.000000  
50%                  5.000000           5.000000           1.000000  
75%                  8.000000           6.000000           2.000000  
max                 10.000000           8.000000           3.000000  

[8 rows x 31 columns]

In [16]:
df.columns

Index(['cliente_id', 'genero', 'edad', 'pais', 'ciudad', 'segmento_cliente',
       'es_mayor', 'tiene_pareja', 'tiene_dependientes', 'latitud', 'longitud',
       'borough', 'codigo_postal', 'estado', 'fecha_registro',
       'ingreso_mediano', 'densidad_poblacional', 'tipo_contrato',
       'antiguedad', 'cargo_mensual', 'ingresos_totales', 'metodo_pago',
       'canal_registro', 'errores_pago', 'descuento_aplicado',
       'aumento_precio_3m', 'facturacion_sin_papel', 'servicio_telefono',
       'lineas_multiples', 'tipo_internet', 'seguridad_online',
       'respaldo_online', 'proteccion_dispositivo', 'soporte_tecnico',
       'streaming_tv', 'streaming_peliculas', 'nivel_riesgo', 'score_riesgo',
       'conexiones_mensuales', 'dias_activos_semanales', 'promedio_conexion',
       'caracteristicas_usadas', 'tasa_crecimiento_uso',
       'dias_ultima_conexion', 'tickets_soporte', 'tiempo_resolucion',
       'tipo_queja', 'escaladas', 'puntuacion_csat', 'puntuacion_nps',
       'tasa_

Definir target y eliminar columnas innecesarias

In [17]:
TARGET = "cancelacion"

cols_to_drop = [
    "cliente_id",
    "fecha_registro",
    "fecha_ultimo_pago",
    "ultimo_contacto_soporte"
]

df = df.drop(columns=cols_to_drop, errors="ignore")

print(df.shape)

(9701, 63)


Separar X y y

In [18]:
X = df.drop(columns=[TARGET])
y = df[TARGET]

print(X.shape, y.shape)

(9701, 62) (9701,)


X train y X test

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

print("Train:", X_train.shape)
print("Test:", X_test.shape)

Train: (7275, 62)
Test: (2426, 62)


In [20]:
cat_cols = X_train.select_dtypes(include="object").columns.tolist()
num_cols = X_train.select_dtypes(exclude="object").columns.tolist()

print("Categóricas:", len(cat_cols))
print("Numéricas:", len(num_cols))

Categóricas: 32
Numéricas: 30


Preprocesamiento por imputación

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

num_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_pipeline, num_cols),
        ("cat", cat_pipeline, cat_cols)
    ]
)

#Modelo base

In [22]:
from sklearn.linear_model import LogisticRegression

model = Pipeline(steps=[
    ("preprocess", preprocessor),
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
])

model.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['edad', 'es_mayor',
                                                   'codigo_postal',
                                                   'ingreso_mediano',
                                                   'densidad_poblacional',
                                                   'antiguedad', 'errores_pago',
                                                   'conexiones_mensuales',
                                                   'dias_activos_semanales',
                                                   'promedio_conexion',
                                                   'caracteristicas_u...
                                                   'descuento_aplicado',
                                                   'aumento_precio_3m',
                                                   'facturacion_sin_papel',
                                                   'servicio_telefono',
                                                   'lineas_multiples',
                                                   'tipo_internet',
                                                   'seguridad_online',
                                                   'respaldo_online',
                                                   'proteccion_dispositivo',
                                                   'soporte_tecnico',
                                                   'streaming_tv',
                                                   'streaming_peliculas',
                                                   'nivel_riesgo',
                                                   'score_riesgo', 'tipo_queja', ...])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [23]:
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

In [24]:
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, roc_auc_score

acc = accuracy_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_proba)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", round(acc, 4))
print("Recall:", round(rec, 4))
print("ROC AUC:", round(auc, 4))
print("Matriz de confusión:\n", cm)

Accuracy: 0.9514
Recall: 0.8556
ROC AUC: 0.9494
Matriz de confusión:
 [[1982   63]
 [  55  326]]


#Ajuste del modelo

In [25]:
from sklearn.metrics import precision_score

thresholds = np.arange(0.05, 0.95, 0.05)

rows = []

for t in thresholds:
    y_pred_t = (y_proba >= t).astype(int)
    prec = precision_score(y_test, y_pred_t)
    rec = recall_score(y_test, y_pred_t)
    rows.append([t, prec, rec])

df_thr = pd.DataFrame(rows, columns=["threshold", "precision", "recall"])
df_thr

threshold  precision    recall
0        0.05   0.354902  0.950131
1        0.10   0.503671  0.900262
2        0.15   0.621771  0.884514
3        0.20   0.712154  0.876640
4        0.25   0.757506  0.860892
5        0.30   0.795122  0.855643
6        0.35   0.815000  0.855643
7        0.40   0.831633  0.855643
8        0.45   0.838046  0.855643
9        0.50   0.838046  0.855643
10       0.55   0.838046  0.855643
11       0.60   0.840206  0.855643
12       0.65   0.840206  0.855643
13       0.70   0.840206  0.855643
14       0.75   0.839793  0.853018
15       0.80   0.839793  0.853018
16       0.85   0.839378  0.850394
17       0.90   0.838275  0.816273

In [26]:
t = 0.30
y_pred_30 = (y_proba >= t).astype(int)

from sklearn.metrics import confusion_matrix, precision_score, recall_score

cm_30 = confusion_matrix(y_test, y_pred_30)
prec_30 = precision_score(y_test, y_pred_30)
rec_30 = recall_score(y_test, y_pred_30)

print("Threshold:", t)
print("Precision:", round(prec_30, 4))
print("Recall:", round(rec_30, 4))
print("Matriz de confusión:\n", cm_30)

Threshold: 0.3
Precision: 0.7951
Recall: 0.8556
Matriz de confusión:
 [[1961   84]
 [  55  326]]


Obtener probabilidades de churn

In [28]:
y_prob = model.predict_proba(X_test)[:, 1]

Curva Precision–Recall

In [29]:
from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(y_test, y_prob)

Tabla de trade-off

In [30]:
pr_df = pd.DataFrame({
    "threshold": thresholds,
    "precision": precision[:-1],
    "recall": recall[:-1]
})

pr_df.head()

threshold  precision  recall
0   0.000308   0.157049     1.0
1   0.000349   0.157113     1.0
2   0.000422   0.157178     1.0
3   0.000445   0.157243     1.0
4   0.000457   0.157308     1.0

In [31]:
pr_df.iloc[::50]

threshold  precision    recall
0      0.000308   0.157049  1.000000
50     0.000921   0.160354  1.000000
100    0.001116   0.163801  1.000000
150    0.001346   0.167399  1.000000
200    0.001549   0.171159  1.000000
250    0.001722   0.175092  1.000000
300    0.001897   0.179210  1.000000
350    0.002135   0.183526  1.000000
400    0.002364   0.188055  1.000000
450    0.002560   0.192814  1.000000
500    0.002808   0.197819  1.000000
550    0.003061   0.203092  1.000000
600    0.003457   0.208653  1.000000
650    0.004018   0.214527  1.000000
700    0.004364   0.220742  1.000000
750    0.005027   0.227327  1.000000
800    0.006034   0.234317  1.000000
850    0.007391   0.241751  1.000000
900    0.009727   0.249672  1.000000
950    0.013445   0.256775  0.994751
1000   0.017745   0.265077  0.992126
1050   0.022820   0.272529  0.984252
1100   0.026498   0.281297  0.979003
1150   0.029375   0.288401  0.965879
1200   0.033342   0.300163  0.965879
1250   0.036590   0.312925  0.965879
1300   0.040456   0.324156  0.958005
1350   0.043940   0.339219  0.958005
1400   0.048998   0.352827  0.950131
1450   0.055333   0.367828  0.942257
1500   0.061865   0.384449  0.934383
1550   0.068707   0.400685  0.921260
1600   0.075837   0.420097  0.910761
1650   0.082386   0.444588  0.905512
1700   0.090264   0.473829  0.902887
1750   0.101690   0.507396  0.900262
1800   0.117405   0.543131  0.892388
1850   0.132699   0.588542  0.889764
1900   0.161116   0.638783  0.881890
1950   0.195593   0.701681  0.876640
2000   0.267962   0.769953  0.860892
2050   0.893614   0.840426  0.829396
2100   0.936794   0.843558  0.721785
2150   0.950084   0.858696  0.622047
2200   0.959284   0.867257  0.514436
2250   0.964712   0.875000  0.404199
2300   0.972007   0.865079  0.286089
2350   0.977844   0.881579  0.175853
2400   0.986043   0.846154  0.057743

In [32]:
best_threshold = 0.17

y_pred_custom = (y_prob >= best_threshold).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred_custom))
print("Recall:", recall_score(y_test, y_pred_custom))
confusion_matrix(y_test, y_pred_custom)

Accuracy: 0.9097279472382522
Recall: 0.8818897637795275


array([[1871,  174],
       [  45,  336]])

Reajuste de modelo

In [33]:
t = 0.40
y_pred_40 = (y_proba >= t).astype(int)

cm_40 = confusion_matrix(y_test, y_pred_40)
prec_40 = precision_score(y_test, y_pred_40)
rec_40 = recall_score(y_test, y_pred_40)

print("Threshold:", t)
print("Precision:", round(prec_40, 4))
print("Recall:", round(rec_40, 4))
print("Matriz de confusión:\n", cm_40)

print("Clientes en riesgo:", cm_40[0,1] + cm_40[1,1])
print("Porcentaje base:", (cm_40[0,1] + cm_40[1,1]) / len(y_test))

Threshold: 0.4
Precision: 0.8316
Recall: 0.8556
Matriz de confusión:
 [[1979   66]
 [  55  326]]
Clientes en riesgo: 392
Porcentaje base: 0.1615828524319868


Métricas

Recall = 331 / (331 + 50) = 0.87

Clientes en riesgo = 139 + 331 = 470

% base ≈ 19%

Se detecta el 87% del churn
Con solo 19% de la base impactada

Buen balance costo–beneficio.

#Serialización

In [34]:
import joblib

joblib.dump(model, "modelo_regresion_logistica.pkl")

['modelo_regresion_logistica.pkl']

Carga del modelo

In [35]:
modelo_cargado = joblib.load("modelo_regresion_logistica.pkl")

probas_nuevas = modelo_cargado.predict_proba(X_test)[:, 1]
pred_nuevas = (probas_nuevas >= 0.40).astype(int)

confusion_matrix(y_test, pred_nuevas)

array([[1979,   66],
       [  55,  326]])